ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';

ALTER TABLE "BookingInquiry" ADD COLUMN IF NOT EXISTS "eventType" TEXT;
ALTER TABLE "BookingInquiry" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
